apiVersion: sources.knative.dev/v1alpha2
kind: ApiServerSource
metadata:
 name: testevents
spec:
 serviceAccountName: events-sa
 mode: Resource
 resources:
   - apiVersion: v1
     kind: Event
 sink:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: event-display-nodejs 