apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: test-sink-binding
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: sink-binding

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display-nodejs
  ceOverrides:
    extensions:
      sink: bound