apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operators
  namespace: openshift-marketplace
spec:
  source: redhat-operators
  targetNamespace: openshift-operators 
  packages: serverless-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: additional-operators
  namespace: openshift-marketplace
spec:
  source: community-operators
  targetNamespace: openshift-operators 
  packages: knative-kafka-operator,strimzi-kafka-operator
