apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: strimzi-kafka-operator 
  source: community-operators 
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-operators
spec:
  channel: "4.5"
  name: serverless-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: knative-kafka-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: knative-kafka-operator 
  source: community-operators 
  sourceNamespace: openshift-marketplace